---
- name: Install Nginx on EC2 servers of autoscaling
  hosts: webservers
  become: yes

  tasks:
    - name: update packages
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes